### ISSUE TITLE
format `date-time` (with actual time part) not working

### ISSUE THREAD

**Issue by x1B** [koumoul-dev/vuetify-jsonschema-form#1]
Hi, this project is looking quite interesting!

Playing around with it, I noticed that the `date-time` format for strings is not really working right now, because the `v-date-picker` only manipulates the date portion of the value.

I prepared a fix that uses the [darrenfang/vuetify-datetime-picker](https://github.com/darrenfang/vuetify-datetime-picker/). It is probably still lacking some features, but may be a start for date-time support:

https://github.com/x1B/vuetify-jsonschema-form/commit/1408dee4d90d613f7706a1a858e2a3793e6de561

Feel free to pick these changes, or let me know if I should open a PR. Best, Michael

**Comment by albanm** [comment]
Thanks !

I will merge this soon, it looks like a worthy addition.

**Comment by chetanpai23** [comment]
Is this feature date-time  format available ?

**Comment by Flayshon** [comment]
+1 to this. looking forward to v1!

**Comment by albanm** [comment]
It is getting closer. Unfortunately it is a struggle to find the time to finish a proper release.

Preview available [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/render-functions/).

**Comment by Flayshon** [comment]
@albanm I'm testing v1.2.0 and, although the date-time picker is showed correctly now, the form field is not updated when I click on the minute. Looking at [this example's source from Vuetify docs](https://vuetifyjs.com/en/components/time-pickers/#in-dialog-and-menu), this would be made by adding something like this to the component or to an Ok/Cancel button:

`@click:minute="$refs.FormFieldRef.save(time)"`

Since you're using render functions, I don't know exactly what would be the equivalent code...

Vjsf version: 1.2.0
Vue.js version: 2.6.10 (can't upgrade atm due to a bug that breaks v-calendar)
Vuetify version: 2.2.18

**Comment by albanm** [comment]
I did not see what you describe. The models were modified, but I did find a few bugs around time management. I just published a version that fixes those bugs.

I do not use ok / cancel buttons, the model is bound on each modification and you simply close the menu by clicking outside when you are done.

Does [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#date-picker) work for you ?

**Comment by Flayshon** [comment]
@albanm Upon further inspection/testing with v1.3.0, I realized this keeps happening when the date-time property is placed inside an [editable array](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples/#editable-array).

I made a gist with the [exact code I'm using](https://gist.github.com/Flayshon/4415aca0fc22e09e9ecc7d077f402d7e) if you wanna take a look.

the fields "start_date" and "end_date" work as you described, but the properties "start" and "end" inside the array "time_slots" do not work. Am I doing something wrong here?

**Comment by albanm** [comment]
Fixed. A reactivity bug in editable arrays.

I've added a date in [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#editable-array) to illustrate.

**Comment by Flayshon** [comment]
Reactivity works, but now the dates being added to the form fields are wrong. This happens both in my form and your example. And it's not even a consistent pattern either...for date-time format on editable array, clicking on April 1 gives me March 29. For date-only format without editable array, clicking on April 4 gives me April 3.

**Comment by albanm** [comment]
Are you sure your don't mix things because of your timezone ?

The date is stored in the model with your timezone as a suffix. If I parse this in js and reserialize with toISOString I can get a different day because of timezone offset.

For example I am currently in gmt+2, if I click on today at 12:00 AM I get this in the model: "2020-04-04T00:00:00+02:00"

If I parse and reserialize this I get the day before at 10pm in standard gmt time : new Date('2020-04-04T00:00:00+02:00').toISOString() => 2020-04-03T22:00:00.000Z

In my opinion this is the proper behavior.

I you want your application to ignore the original user's timezone, you can always remove the offset suffix.

**Comment by Flayshon** [comment]
But if it's a timezone problem, why does it keeps happening for

- date fields (no time)
- date-time fields when I use values like 3pm (my timezone is GMT-3). I would understand a 3-hour offset, but not multiple days

I'm still very confused by this behavior. [I made a screen capture if you wanna see what I'm seeing](https://www.loom.com/share/eefd54ce89ee4c76b24bb45a776a9bf8).

**Comment by albanm** [comment]
You are right: not normal for a date field without time and not normal to have multiple days offset.

I will look into this and thanks for the detailed feedback.

**Comment by albanm** [comment]
there was indeed a bug with negative timezone offsets. It showed the day prior, and if you reopened the picker you got another day prior, etc.

Hopefully this is fixed in v1.3.2.

**Comment by Flayshon** [comment]
It seems to be working for me now! Thanks!
