### ISSUE TITLE
Using OneOf force to have a sub key

### ISSUE THREAD

**Issue by MaxSPRTL** [koumoul-dev/vuetify-jsonschema-form#139]
Hello there,

I try to make a form composed of :
 - different attributes depending on the answer of a field
 - a common part

Here is the schema :
```javascript
const schema = {
  "type": "object",
  "properties": {
    "sub-key": {
      "type": "object",
      "title": "Select your race",
      "oneOf": [
        {
          "title": "orc",
          "properties": {
            "race": {
              "type": "string",
              "const": "orc"
            },
            "strength": {
              "type": "integer",
            }
          }
        },
        {
          "title": "human",
          "properties": {
            "race": {
              "type": "string",
              "const": "human"
            },
            "agility": {
              "type": "integer",
            }
          }
        }
      ]
    },
    "name": {
      "type": "string"
    }
  }
}
```

The oneOffield define the race of the character and depending on that your character have strength or agility. The common part is the name.

I want all the attributes to be at the model's root but the problem using oneOf is that you must add a key to declare it ("sub-key" in the exemple)

So the model looks like this :
```
{ "sub-key": { "race": "orc", "strength": 12 }, "name": "Groumf" } 
```

But I want my model to look like this :

```
{ "race": "orc", "strength": 12, "name": "Groumf" } 
```

I was wondering if there are any ways to achieve this. Also the common part of the schema is way much longer in my project so is the differents parts.

Thanks you.

Edit: I could add a function for destructuring the model for oneOf with a specific tag but since I use the same schema to edit my objects, I should find a way to rebuild the model to fit the schema. And this for every keys. I don't want to add my own functions on top of the library...

**Comment by albanm** [comment]
If I understand correctly you can achieve this, see https://codepen.io/albanm/pen/XWdMwNM

But you won't have control of where the oneOf will be rendered, it will always be after the other properties. I don't see how to improve on this, but I am open to suggestions.

**Comment by MaximeSauvage1** [comment]
Thanks for your quick reply :)

I've already tried your solution but as you say I don't have control where the oneOf will be render... It's the correct behavior but the fact that is rendering after the properties is a problem...

Also, with your solution, the schema can only have one field "oneOf"... Maybe adding adding a field like "shouldDestructuring: true" in the oneOf object will be a solution. I've already done that by adding a custom attribute in the schema that is "editable: true". I use my Backend to convert non editables fields in readOnly. But it's not a clean solution since I add my own logic on top of your library... I try to avoid doing the same again.

I've started to check for a workaround. If I keep this idea I'll make a Pull Request ;)
