### ISSUE TITLE
Can't make Editable array a required field

### ISSUE THREAD

**Issue by dailyenergy** [koumoul-dev/vuetify-jsonschema-form#191]
I'm able to make the fields of an editable array required but not the editable array its self, tried setting it to required tried setting minitems: 1, both don't do anything. I'm i doing something wrong or is it a missing issue to the futher awesome library

**Comment by albanm** [comment]
I think the minItems validation works, see this example https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#validation-basic

I see that you wrote "miniItems" in this issue instead of "minItems", maybe you have the same typo in the code ? Or maybe there is a bug that is not covered by the example, in this case please try to provide a codepen (click on the codepen icon on the example then edit and save the codepen).

About required, it is expected to do nothing in this case as the array is created empty automatically, so it exists and never breaks this validation rule.
