### ISSUE TITLE
Formatting phone numbers?

### ISSUE THREAD

**Issue by q00u** [koumoul-dev/vuetify-jsonschema-form#194]
#183 asks about this, and you point to [this example in the doc](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots)

The example says to look at `custom-string1` in the example.

But, in the example, where is `custom-string1` defined? stringProp3 doesn't appear to display any differently than any other text box.

**Comment by albanm** [comment]
custom-string1 is a slot defined in the template of the example, it is referenced by stringProp3 that is rendered as a basic html text field (as defined in the matching slot) instead of the usual v-text-field.

This [new example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers) is more complete on the subject of writing custom components, which was the original question asked in the issue you reference.

Right now adding a custom component in a slot is the only way to do this. But I will tag this issue as a feature request and think about adding the functionality in an easier way. I need to think about it in more details, but maybe something like that would do the trick:

  - add a concept of formatting functions passed in the options and referenced in the schema using a x-format annotation or something similar
  - add a few standard values for x-display that would define in a single instruction a formatting function, a validation rule and a prepend icon

I can't say when I will be able to spend some time on this subject. If you need this soon you should look into the first solution of using slots and custom components.
