### ISSUE TITLE
[SOLVED] How to set the date to be default format YYYY-MM-DD?

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#224]
Hi there

for the format-date, how do I set the date to be in yyyy-mm-dd format?

Thanks

**Comment by albanm** [comment]
Hello,

In the model the date will always be stored using the iso format, otherwise the json schema would not validate.

If you are talking about the format that is shown to the user, it is based on the current locale but you can customize it by replacing the formatting function (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration).
