### ISSUE TITLE
How to give 'string' a search suggestions from local?

### ISSUE THREAD

**Issue by cheezone** [koumoul-dev/vuetify-jsonschema-form#256]
The data is saved locally

**Comment by albanm** [comment]
I just added an example that use the 'x-fromData' annotation to fill a select, see https://koumoul-dev.github.io/vuetify-jsonschema-form/master/examples#select

It is also possible to transform the select into a combobox using the x-display=combobox so that the values are only suggestions.

Please close the issue if you are ok with the response.

**Comment by cheezone** [comment]
Thanks!
