### ISSUE TITLE
x-props partially working

### ISSUE THREAD

**Issue by mttmccb** [koumoul-dev/vuetify-jsonschema-form#281]
You'll see it in the example pen, that the `chips` property isn't being applied https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#vuetify-props, I tried on my dev environment and `hide-selected` did so unsure if it's a problem with this component. When inspecting the component (suing vue dev tools) the property is passed through but it's not rendered that way. Any ideas or possible workarounds for this?

**Comment by albanm** [comment]
Ah yes, sorry I missed this regression.

In order to support more cases vjsf defines the selection slot of the v-select component. Therefore some standard props are ignored. I don't really know what to do about that. I need to think about it, I see a few possibilities:

  - re-implement some of the props to recreate the original vuetify behavior (can create quite a lot of complexity)
  - either find a way to stop using the slot, or separate the cases where the slot is really necessary (I don't remember exactly what they are) and stop using it the rest of the time
  - just let it go as it is and fix the doc

**Comment by xfavalon** [comment]
Hi! 

I found a similar issue when I tried to pass a vuetify property of _v-expansion-panel_ through 'x-props' in order to make a panel always opened or expanded. The property was readonly: true or disabled: true. But didn't work. 

I checked ObjectContainer.js and I noticed that x-props are missing as a parameter in the render function of _v-expansion-panel_ component. Check out line 132. 

So, to solve my issue I added this: **props: { ...schema['x-props'] }**
![image](https://user-images.githubusercontent.com/90746804/134901525-fbb84559-1bdb-4b76-b553-05d7ab462fab.png)

I don´t know if this is a bug or I'm missing another way to achieve the same result but it works for me. 

Thanks!

**Comment by IOIIOOIO** [comment]
I'd like to add a request for `persistent-placeholder` support. We use it on all our inputs so it would be very helpful.

Currently, this is my solution - but it has had side effects on one or two inputs in the project where we don't want the effect.

 **Globally, in a .scss file:**

```
.v-text-field .v-label {
	transform: translateY(-18px) scale(0.81) !important;
}
```

**Comment by albanm** [comment]
Doesn't it already work with option fieldProps: {persistentPlaceholder: true} ?

**Comment by IOIIOOIO** [comment]
> Doesn't it already work with option fieldProps: {persistentPlaceholder: true} ?

Perhaps I'm doing it wrong? I'm not sure where to put that in this example:

```
schema: {
		"type": "object",
		"properties": {
			"stringProp": {
				"fieldProps": {"persistentPlaceholder": true},
				"type": "string",
				"title": "I'm a string",
				"description": "This description is used as a help message.",
			},
		}
	},
```

**Comment by albanm** [comment]
```
schema: {
		"type": "object",
		"properties": {
			"stringProp": {
				"x-options": {"fieldProps": {"persistentPlaceholder": true}},
				"type": "string",
				"title": "I'm a string",
				"description": "This description is used as a help message.",
			},
		}
	},
```

**Comment by IOIIOOIO** [comment]
I'm a numbskull. Just realised that as you replied. Thanks!
