### ISSUE TITLE
Applying Subschemas Conditionally

### ISSUE THREAD

**Issue by johngtb** [koumoul-dev/vuetify-jsonschema-form#290]
Hi, any plans on supporting dependentRequired and dependentSchemas as stated [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html)?

**Comment by albanm** [comment]
Sure, looks quite easy. But I can't say when unfortunately.

**Comment by marr** [comment]
I was thinking that `dependentRequired` would be a way to implement a change password flow, conditionally requiring a "confirm password" field. 
Since `dependentRequired` is not available in vjsf yet, is there a way to do this using the standard if/then/else or the expression syntax to achieve that result? If so, how?
