### ISSUE TITLE
how to download the latest release? 

### ISSUE THREAD

**Issue by jgunstone** [koumoul-dev/vuetify-jsonschema-form#338]
hi there, 
I've been playing with this repo and it works great - 
I wanted to know how to install the latest release? 

the repo is up to [2.11.1](https://github.com/koumoul-dev/vuetify-jsonschema-form/commit/decd15a13b56fc423e19b9857821c46ea16f886d), but the latest release is 1.16 and on npm / jsdelivr its at 0.36.4... 

many thanks

**Comment by albanm** [comment]
You are looking at the old package name, the library is now published on @kououl/vjsf since v1.

I think the documentation is up to date, if there is still a reference to the wrong version somewhere please let me know.

Also I don't really use github releases, I know I should, mostly for clarity and as a changelog.

**Comment by jgunstone** [comment]
my mistake - thanks for the [clarification](https://www.npmjs.com/package/@koumoul/vjsf)
