### ISSUE TITLE
Time is not saved as locale string

### ISSUE THREAD

**Issue by dominikhorn93** [koumoul-dev/vuetify-jsonschema-form#354]
datetime is saved correctly as locale string, time ist not.
Is there a reason for this or is it bug?

![image](https://user-images.githubusercontent.com/27461050/165933823-8d2fa958-c6c4-4817-acee-11a91a330ca1.png)

**Comment by albanm** [comment]
This is noted in the doc https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#date-picker

Times alone are stored without representing the offset but also without applying it in the first place. Meaning that if the user select 00:00 we will store 00:00:00Z whatever his timezone. This is because without the context of a date timezone management becomes meaningless.

**Comment by dominikhorn93** [comment]
Thanks for pointing that out, I had missed it.
That makes sense, of course. A user in our software had modeled Date and Time separately instead of taking the Date Time. That's when it came up.
