### ISSUE TITLE
please update your documentation

### ISSUE THREAD

**Issue by selobu** [koumoul-dev/vuetify-jsonschema-form#77]
for example

Import vjsf into your project

```
import VJsf from "@koumoul/vuetify-jsonschema-form/lib/";
import "@koumoul/vuetify-jsonschema-form/dist/main.css";

Vue.component("VJsf", VJsf);

```

**Comment by albanm** [comment]
I think the doc is up to date, maybe I missed something but I don't know what.

Maybe you got confused by the module name change. The project is still called vuetify-jsonschema-form on github, but the npm module is called @koumoul/vjsf since the recent release of v1. See https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/0to1
